name: Release
# https://github.com/bent10/monorepo-starter/blob/main/docs/recipes/release-automation.md

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Releasing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - run: yarn install --frozen-lockfile --check-files
      - run: yarn lerna run prepare --stream

      # https://github.com/dhoulb/multi-semantic-release
      - name: Semantic release
        # use `--ignore-packages` to ignore packages on bumping process
        # npx multi-semantic-release --ignore-packages=packages/a/**,packages/b/**
        run: npx multi-semantic-release
        env:
          GITHUB_TOKEN: ${{ github.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
